const errorTypeIsNotReport = [
  'ERR_APP_VERSION_IS_INVALID',
  'ERR_ACCOUNT_INVALID_PASSCODE',
  'ERR_ACCOUNT_NOT_FOUND',
  'ERR_STATE_LIMIT_EXCEED',
  'ERR_FRIEND_LIMIT',
  'ERR_OFFICIAL_ACCOUNT_LIMIT',
  'ERR_ACCOUNT_INVALID_PHONE_NUMBER',
  'ERR_ACCOUNT_COUNTRY_NOT_SUPPORT',
  'ERR_ACCOUNT_INVALID_PASSCODE',
  'ERR_SERVICE_ON_MAINTENANCE_MODE',
  'ERR_FILE_UPLOAD_NOT_FOUND',
];
