// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_sit.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRUUDkWiebw5W5MiyZ9zAwY6wRuP1-OAY',
    appId: '1:575432061589:android:8ed1cafadcb8f9a35ea19c',
    messagingSenderId: '575432061589',
    projectId: 'uchat-dev-d3114',
    databaseURL: 'https://uchat-dev-d3114-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'uchat-dev-d3114.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBObNWn8byKKBAMPAtP7Tq7y42MJ51XIcg',
    appId: '1:575432061589:ios:c3394258fff365e05ea19c',
    messagingSenderId: '575432061589',
    projectId: 'uchat-dev-d3114',
    databaseURL: 'https://uchat-dev-d3114-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'uchat-dev-d3114.firebasestorage.app',
    androidClientId: '575432061589-1jfntoh1pib81j2ecptqrguqe574fvke.apps.googleusercontent.com',
    iosClientId: '575432061589-m0emvfrsqi256pfiubd05s86krv5mdj3.apps.googleusercontent.com',
    iosBundleId: 'social.uchat.messenger.sit',
  );
}
