source "https://rubygems.org"

gem "cocoapods", "~> 1.12", ">= 1.12.1"
gem 'fastlane', '>= 2.0'
gem "dotenv"
gem "csv"
gem "fastlane-plugin-flutter_version", "~> 1.0", ">= 1.0.1"
gem "fastlane-plugin-firebase_app_distribution"


plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)

gem "mutex_m", "~> 0.2.0"

gem "abbrev", "~> 0.1.2"

gem "xcodeproj", "~> 1.27"
