/// Flutter icons Uchat
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Uchat
///      fonts:
///       - asset: fonts/Uchat.ttf
///
///
///
library;

import 'package:flutter/widgets.dart';

class UChatIcons {
  UChatIcons._();

  static const _kFontFam = 'Uchat';
  static const String? _kFontPkg = null;
  static const IconData addFriendGroup = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData addFriend = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData archived = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData block = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cameraFill = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData createChat = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData deleteFill = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData homeFill = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData imageFill = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData image = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData link = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData magnifyingGlass = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData messageFill = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData muted = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencil = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData qrCode = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scan = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settingsFill = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData videoCall = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pin = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pushpin = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const _kFontFamPinMuteHideDelete = 'PinMuteHideDelete';

  static const IconData pinIcon = IconData(0xe800, fontFamily: _kFontFamPinMuteHideDelete, fontPackage: _kFontPkg);
  static const IconData muteIcon = IconData(0xe801, fontFamily: _kFontFamPinMuteHideDelete, fontPackage: _kFontPkg);
  static const IconData hideIcon = IconData(0xe802, fontFamily: _kFontFamPinMuteHideDelete, fontPackage: _kFontPkg);
  static const IconData deleteIcon = IconData(0xe803, fontFamily: _kFontFamPinMuteHideDelete, fontPackage: _kFontPkg);
  static const IconData unmuteIcon = IconData(0xe804, fontFamily: _kFontFamPinMuteHideDelete, fontPackage: _kFontPkg);
  static const IconData unpinIcon = IconData(0xe805, fontFamily: _kFontFamPinMuteHideDelete, fontPackage: _kFontPkg);
}
