# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  lane :build do |options|
    flavor = options[:flavor] || ""
    build_number = ENV["BUILD_NUMBER"].to_i
    build_name = ENV["BUILD_VERSION"] || flutter_version()["version_name"]

    Dir.chdir "../.." do
      #       sh("fvm", "flutter", "build", "appbundle", "--release", "--obfuscate", "--split-debug-info=build/app/outputs/symbols", "--build-name=#{build_name}", "--build-number=#{build_number}")

      if flavor == ""
        sh("fvm flutter build appbundle --release --flavor prd --build-name=#{build_name} --build-number=#{build_number}")
        destAabDir = "build/app/outputs/bundle/release"
        sh("mkdir -p #{destAabDir}")
        sh("cp build/app/outputs/bundle/prdRelease/app-prd-release.aab build/app/outputs/bundle/release/uchat.aab")
      else
        sh("fvm flutter build appbundle --release --flavor #{flavor} --build-name=#{build_name} --build-number=#{build_number}")

        aab_files = Dir["build/app/outputs/bundle/#{flavor}*/app*.aab"]

        if aab_files.empty?
          UI.user_error!("Not found .aab file")
        end
        UI.message("AAB Files: #{aab_files}")

        destAabDir = "build/app/outputs/bundle/release"
        sh("mkdir -p #{destAabDir}")
        sh("cp -rf #{aab_files.first} #{destAabDir}/uchat.aab")
      end
    end
  end

  lane :build_apk do
    build_number = ENV["BUILD_NUMBER"].to_i
    build_name = ENV["BUILD_VERSION"] || flutter_version()["version_name"]

    Dir.chdir "../.." do
      #       sh("fvm", "flutter", "build", "appbundle", "--release", "--obfuscate", "--split-debug-info=build/app/outputs/symbols", "--build-name=#{build_name}", "--build-number=#{build_number}")
      sh("fvm flutter build apk --release --build-name=#{build_name} --build-number=#{build_number}")
      sh("cp build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/uchat.apk")
    end
  end

  lane :deploy_internal do |options|
    build_number = ENV["BUILD_NUMBER"].to_i
    build_name = ENV["BUILD_VERSION"] || flutter_version()["version_name"]
    package_name = options[:package_name] || "social.uchat"

    UI.message("Deploying #{package_name} with version #{build_number} (#{build_name})")

    upload_to_play_store(
      track: 'internal',
      aab: '../build/app/outputs/bundle/release/uchat.aab',
      release_status: 'completed',
      rollout: '1',
      skip_upload_metadata: true,
      skip_upload_changelogs: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      package_name: package_name,
      version_name: build_number.to_s + ' ('+build_name.to_s+')',
    )
  end

  lane :build_dev do
    build(flavor: "dev", package_name: "social.uchat.messenger.dev")
  end

  lane :deploy_dev do
    deploy_internal(package_name: "social.uchat.messenger.dev")
  end

  lane :dev do
    build_dev
    deploy_dev
  end

  lane :build_uat do
    build(flavor: "uat", package_name: "social.uchat.messenger.uat")
  end

  lane :deploy_uat do
    deploy_internal(package_name: "social.uchat.messenger.uat")
  end

  lane :uat do
    build_uat
    deploy_uat
  end

  lane :build_sit do
    build(flavor: "sit", package_name: "social.uchat.messenger.sit")
  end

  lane :deploy_sit do
    deploy_internal(package_name: "social.uchat.messenger.sit")
  end

  lane :sit do
    build_sit
    deploy_sit
  end

  lane :build_prd do
    build(flavor: "prd", package_name: "social.uchat")
  end

  lane :deploy_prd do
    deploy_internal(package_name: "social.uchat")
  end

  lane :prd do
    build_prd
    deploy_prd
  end
end