name: Patrol Minimal Test
on:
  push:
    branches:
      - 'test/automate'

jobs:
  ios-test:
    runs-on: self-hosted
    steps:
      - name: 🚀 Test Runner is Alive
        run: echo "Hello World! Runner is working!"